exports.data = [
  {
    programId: '1',
    program: 'ESM_BKG_0079',
    fileName: 'opus_video1.mp4',
    remark: '',
    src: 'https://www.youtube.com/embed/3xccmeAsy8g',
    average: '42',
    count: '33',
    rating: 5,
    feedbackContent: 'Excellent!',
    tips: 'In case, dangerous cargo, please check whether company accept thoes DG cargo or not in advance ',
    files: []
  },
  {
    programId: '2',
    program: 'ESM_BKG_0079',
    fileName: 'opus_video2.mp4',
    remark: '',
    src: 'https://www.youtube.com/embed/BwZs3H_UN3k',
    average: '42',
    count: '33',
    rating: 4,
    feedbackContent: 'Good!',
    tips: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. ',
    files: []
  },
  {
    programId: '3',
    program: 'ESM_BKG_0079',
    fileName: 'opus_video3.mp4',
    remark: '',
    src: 'https://www.youtube.com/embed/YaykGT215b4',
    average: '42',
    count: '33',
    rating: 3,
    feedbackContent: 'Fantastic!',
    tips: 'In case, dangerous cargo, please check whether company accept thoes DG cargo or not in advance ',
    files: []
  },
  {
    programId: '4',
    program: 'ESM_BKG_0079',
    fileName: 'opus_video4.mp4',
    remark: '',
    src: 'https://www.youtube.com/embed/GatNL0mmQGc',
    average: '42',
    count: '33',
    rating: 2,
    feedbackContent: 'Fantastic!',
    tips: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. ',
    files: []
  },
  {
    programId: '5',
    program: 'ESM_BKG_0079',
    fileName: 'opus_video5.mp4',
    remark: '',
    src: 'https://drive.google.com/file/d/1K8lr7u5q4iUQnfPnCvMy_rHfgpk_eaj_/preview',
    average: '42',
    count: '33',
    rating: 1,
    feedbackContent: 'I dont understand!',
    tips: 'In case, dangerous cargo, please check whether company accept thoes DG cargo or not in advance  ',
    files: []
  },
  {
    programId: '6',
    program: 'ESM_BKG_0079',
    fileName: 'opus_video6.mp4',
    remark: '',
    src: 'https://www.youtube.com/embed/UVbv-PJXm14',
    average: '42',
    count: '33',
    rating: 4,
    feedbackContent: 'Good!',
    tips: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. ',
    files: []
  }
]
